name: identity_document_detection
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  tflite_flutter: ^0.10.4
  camera: ^0.10.5+2
  image: ^4.0.17
  path_provider: ^2.0.15
  image_picker: ^1.0.0
  exif: ^3.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - packages/identity_document_detection/assets/model/document.tflite
    - packages/identity_document_detection/assets/model/classes.txt
